# the base URL of your notes Github pages website
base_url: https://vllmrt.net/dump

# the URL of your notes Github repo
repo_url: https://github.com/robx/dump

# the name for your notes website
name: Dump

# the description of the notes website
description: This is my collection of random notes about tech things.
